spring:
  application:
    name: bankingmanagementwithmvc

  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:bankingmanagementwithmvc

# ThymeLeaf
  thymeleaf:
    template-loader-path: classpath:/templates
    suffix: .html
    cache: false
server:
  port: 9090